### ISSUE TITLE
Extract list of ENV variables

### ISSUE THREAD

**Issue by kluzzebass** [sethvargo/go-envconfig#78] opened 2022-11-24 10:58 UTC
Is there any way to dump a complete list of the ENV variables envcconfig is looking for, possibly with some additional information, like the data type, etc.? Asking the devops people to decode the config struct to get all the ENV vars they need to supply when deploying seems a bit much. I'd prefer to stay on friendly terms with them.

**Comment by sethvargo** [comment] 2022-11-24 16:44
Duplicate of #77

**Closed by sethvargo** 2022-11-24 16:44 UTC
